all:
  children:
    workers:
      hosts:
        worker1:
          ansible_host: worker1.local
          ansible_user: root
          ansible_ssh_private_key_file: /home/vagrant/.ssh/id_ed25519
        worker2:
          ansible_host: worker2.local
          ansible_user: root
          ansible_ssh_private_key_file: /home/vagrant/.ssh/id_ed25519
