all:
  children:
    atnodes:
      hosts:
        atnode00a:
          ansible_host: 10.20.30.12
          ansible_user: vagrant
          ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa
        atnode00b:
          ansible_host: 10.20.30.13
          ansible_user: vagrant
          ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa